# Generated by Django 2.0.5 on 2018-05-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctorant',
            fields=[
                ('doctorant_id', models.AutoField(primary_key=True, serialize=False)),
                ('nationaliter', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('sexe', models.CharField(max_length=10)),
                ('date_naissance', models.DateTimeField()),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('addresse', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=15)),
                ('nom_prenom_mere', models.CharField(max_length=50)),
                ('nom_pere', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
    ]
