# Generated by Django 2.0.5 on 2018-06-01 22:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorant',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
