# Generated by Django 2.0.5 on 2018-05-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorant',
            name='doctorant_id',
        ),
        migrations.AddField(
            model_name='doctorant',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctorant',
            name='date_naissance',
            field=models.DateField(),
        ),
    ]
