# Generated by Django 2.0.5 on 2018-05-30 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0002_auto_20180530_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorant',
            name='nom_pere',
        ),
    ]
