# Generated by Django 2.0.5 on 2018-06-03 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0002_doctorant_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeSoutenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberAccepted', models.IntegerField()),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('sexe', models.CharField(max_length=10)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('addresse', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='demandesoutenance',
            name='Enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignants', to='Administration.Enseignant'),
        ),
        migrations.AddField(
            model_name='demandesoutenance',
            name='doctorant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctorant', to='Administration.Doctorant'),
        ),
    ]
