# Generated by Django 2.0.5 on 2018-05-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0003_remove_doctorant_nom_pere'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorant',
            name='nom_pere',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
