# Generated by Django 2.0.5 on 2018-06-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0003_auto_20180603_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='grade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
