# Generated by Django 2.0.5 on 2018-06-03 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0004_enseignant_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demandesoutenance',
            old_name='Enseignant',
            new_name='enseignant',
        ),
        migrations.AddField(
            model_name='demandesoutenance',
            name='reinscription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reinscription', to='Administration.Reinscription'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demandesoutenance',
            name='numberAccepted',
            field=models.IntegerField(default=0),
        ),
    ]
