# Generated by Django 2.0.5 on 2018-05-30 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0004_doctorant_nom_pere'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorant',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
