# Generated by Django 2.0.5 on 2018-05-30 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0005_doctorant_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorant',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
