# Generated by Django 2.0.5 on 2018-06-03 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0005_auto_20180603_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandesoutenance',
            name='slug',
        ),
    ]
