# Generated by Django 2.0.5 on 2018-06-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0006_remove_demandesoutenance_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandesoutenance',
            name='doctorant',
        ),
        migrations.RemoveField(
            model_name='demandesoutenance',
            name='enseignant',
        ),
        migrations.RemoveField(
            model_name='demandesoutenance',
            name='reinscription',
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='grade',
        ),
        migrations.AddField(
            model_name='enseignant',
            name='Grade',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='DemandeSoutenance',
        ),
    ]
