# Generated by Django 2.0.5 on 2018-05-31 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0006_doctorant_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=10)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
    ]
