# Generated by Django 2.0.5 on 2018-06-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0007_auto_20180603_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='Grade',
            field=models.IntegerField(default=1),
        ),
    ]
