# Generated by Django 2.0.5 on 2018-05-31 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0007_module'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='year',
            new_name='niveau',
        ),
    ]
