# Generated by Django 2.0.5 on 2018-06-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0008_auto_20180603_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignant',
            name='Grade',
        ),
        migrations.AddField(
            model_name='enseignant',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
