# Generated by Django 2.0.5 on 2018-05-31 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0008_auto_20180531_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recourt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('slug', models.SlugField()),
                ('doctorant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Administration.Doctorant')),
            ],
            options={
                'ordering': ['sujet'],
            },
        ),
    ]
