# Generated by Django 2.0.5 on 2018-05-31 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0009_recourt'),
    ]

    operations = [
        migrations.AddField(
            model_name='recourt',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recourt',
            name='doctorant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recours', to='Administration.Doctorant'),
        ),
        migrations.AlterField(
            model_name='recourt',
            name='message',
            field=models.CharField(max_length=2550),
        ),
        migrations.RemoveField(
            model_name='recourt',
            name='slug',
        ),
        migrations.AlterUniqueTogether(
            name='recourt',
            unique_together={('doctorant', 'sujet')},
        ),
    ]
