# Generated by Django 2.0.5 on 2018-06-03 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0009_auto_20180603_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassageGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradeVoulu', models.CharField(max_length=50)),
                ('argument', models.CharField(max_length=2550)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passagegrades', to='Administration.Enseignant')),
            ],
            options={
                'ordering': ['gradeVoulu'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='passagegrade',
            unique_together={('enseignant', 'gradeVoulu')},
        ),
    ]
