# Generated by Django 2.0.5 on 2018-05-31 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0011_sujet'),
    ]

    operations = [
        migrations.AddField(
            model_name='sujet',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sujet',
            name='description',
            field=models.TextField(),
        ),
    ]
