# Generated by Django 2.0.5 on 2018-06-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0011_auto_20180603_1309'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recourt',
            new_name='Recours',
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='grade',
            field=models.CharField(max_length=50),
        ),
    ]
