# Generated by Django 2.0.5 on 2018-05-31 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0012_auto_20180531_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sujet',
            options={'ordering': ['titre']},
        ),
        migrations.RenameField(
            model_name='sujet',
            old_name='nom',
            new_name='titre',
        ),
    ]
