# Generated by Django 2.0.5 on 2018-05-31 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0013_auto_20180531_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reinscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitulerPostGrade', models.CharField(max_length=100)),
                ('intitulerSujet', models.CharField(max_length=100)),
                ('diplomeGraduation', models.CharField(max_length=250)),
                ('nomEncadreur', models.CharField(max_length=100)),
                ('gradeEncadreur', models.CharField(max_length=100)),
                ('nomCoEncadreur', models.CharField(max_length=100)),
                ('gradeCoEncadreur', models.CharField(max_length=100)),
                ('dateRinscription', models.DateField()),
                ('slug', models.SlugField()),
                ('doctorant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reinscriptions', to='Administration.Doctorant')),
            ],
            options={
                'ordering': ['intitulerPostGrade'],
                'get_latest_by': 'dateRinscription',
            },
        ),
    ]
